### ndarray 연산

### 기본 연산

In [2]:
import numpy as np

In [4]:
arr_a= np.arange(1,10).reshape(3,3)
arr_b=np.full_like(arr_a,3)
print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [19]:
# 덧셈
print(arr_a+arr_b)
print(np.add(arr_a,arr_b))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 뺼셈
print(arr_a-arr_b)
print(np.subtract(arr_a,arr_b)) # subtract()

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
# 곱셈
print(arr_a*arr_b)
print(np.multiply(arr_a,arr_b)) # multiply

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
# 나눈셈
print(arr_a/arr_b)
print(np.divide(arr_a,arr_b)) # divide()

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [ ]:
# 특수 연산 1: 거듭제곱
print(arr_a**arr_b)
print(np.power(arr_a,arr_b)) # power() 거듭 제곱
print(np.square(arr_a)) # square() 제곱

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# 특수 연산 2: 몫
print(arr_a//arr_b)
print(np.floor_divide(arr_a,arr_b)) # floor_divide()

[[0 0 1]
 [1 1 2]
 [2 2 3]]
[[0 0 1]
 [1 1 2]
 [2 2 3]]


In [ ]:
# 특수 연산 3: 나머지
print(arr_a%arr_b)
print(np.mod(arr_a,arr_b)) # mod()

[[1 2 0]
 [1 2 0]
 [1 2 0]]
[[1 2 0]
 [1 2 0]
 [1 2 0]]


In [ ]:
# 제곱근
print(np.sqrt(arr_a)) #sqrt()

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


---
### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [28]:
# arr_a=np.arange(1,10).reshape(3,3)

result_arr1=arr_a*np.array([[5,5,5],[5,5,5],[5,5,5]])
result_arr2=arr_a*np.array([[5,5,5]]) # (3,)
result_arr3=arr_a*np.array([5]) # (1,)
result_arr4=arr_a*5 # 스칼라값
print('\n-----(1)-----')
print(result_arr1)
print('\n-----(2)-----')
print(result_arr2)
print('\n-----(3)-----')
print(result_arr3)
print('\n-----(4)-----')
print(result_arr4)


-----(1)-----
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

-----(2)-----
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

-----(3)-----
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

-----(4)-----
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [40]:
arr1=np.array([[1,2,3],[4,5,6]]) # (2,3)
arr2=np.array([5,10,15]) # (3,) 덧셈을 위해 차원을 확장 => [[5,10,15],[5,10,15]]
arr1+arr2

array([[ 6, 12, 18],
       [ 9, 15, 21]])

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]]) # (2,3) 
arr2=np.array([[100],[200]]) # (2,1) 연산을 위해  요소를 확장 => [[100,100,100],[200,200,200]]
arr1+arr2

[[100]
 [200]]


In [46]:
arr1 = np.array([1,2,3]) # (3,)  차원학장 => [[1,2,3],[1,2,3],[1,2,3]]
arr2= np.array([[4],[5],[6]]) # (3,1) 요소확장 => [[4,4,4],[5,5,5],[6,6,6]]
arr1+arr2


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
arr1=np.array([[1,2,3],[1,2,3]]) # (2,3)
arr2=np.array([1,2]) # (2,)
# arr1+arr2 # ValueError: operands could not be broadcast together with shapes (2,3) (2,)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

---
##### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 곱셈은 첫 번째 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 수가 같아야 한다.
    - 연산 결과의 shape은 (첫 번째 행렬 A의 행수, 둡 너째 행렬 B의 열수) 이다.

In [52]:
arr1=np.array([[1,2],
               [3,4]])

arr2=np.array([[5,6],
               [7,8]])
print(arr1 * arr2)
print(arr1.shape,arr2.shape,(arr1 * arr2).shape)

print('\n---행렬곱셈---')
print(np.dot(arr1,arr2))
print(np.dot(arr1,arr2).shape)

[[ 5 12]
 [21 32]]
(2, 2) (2, 2) (2, 2)

---행렬곱셈---
[[19 22]
 [43 50]]
(2, 2)


In [54]:
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[7,8],[9,10],[11,12]])
print(arr3.shape,arr4.shape,np.dot(arr3,arr4).shape)

(2, 3) (3, 2) (2, 2)


### Quiz! shape으로만 결과 판단하기
```
- 첫 번째 행렬 A의 열의 수와 / 두 번째 행렬 B의 행의 수가 같아야 한다.
- 연산 결과의 shape은 (첫 번째 행렬 A의 행수, 두 번째 행렬 B의 열수) 이다.
```

(100,2000) (20000,100) : (100,100)

(20000,100) (100,20000) : (20000,20000)

(100,20000) (100, 20000) : 내적 안됨

In [ ]:
arr=np.array([[1,2,3],[4,5,6]]) # (2,3)

# @ 행렬곱셈
# print(arr @ arr) # (2,3)(2,3)

# .T
print(arr)
print('---------')
print(arr.T) # arr.T = arr의 전치 행렬 (행-열을 교환) # (3,2)

print('---내적----')
print(arr@arr.T) # (2,3) (3,2)

print('---내적----')
# matmul() == @ 내적을 구하는 함수
print(np.matmul(arr,arr.T))

[[1 2 3]
 [4 5 6]]
---------
[[1 4]
 [2 5]
 [3 6]]
---내적----
[[14 32]
 [32 77]]
---내적----
[[14 32]
 [32 77]]


---
##### 연산 함수 및 집계 함수

In [77]:
arr_negative=np.array([[-1,-2],[-100,-200]])
arr_float=np.array([[1.234,5.678],[7.98,10.123]])
arr=np.arange(1,7).reshape(2,3)

In [75]:
# 절대값
np.abs(arr_negative)

array([[  1,   2],
       [100, 200]])

In [ ]:
# 올림/반올림
# arr_float=np.array([[1.234,5.678],[7.98,10.123]])

print(np.ceil(arr_float))
print(np.round(arr_float))
print(np.round(arr_float,2)) #round(인자 , 솟수점 n까지 반올림하여 출력)

[[ 2.  6.]
 [ 8. 11.]]
[[ 1.  6.]
 [ 8. 10.]]
[[ 1.23  5.68]
 [ 7.98 10.12]]


In [81]:
arr_float=np.array([[1.234,-5.678],[-7.98,10.123]])

# 내림 (지정된 수보다 작은 최대 정수)
print(np.floor(arr_float))

# 버림 (절삭)
print(np.trunc(arr_float))

[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [88]:
# 최대값/최소값
# print(arr) arr=np.arange(1,7).reshape(2,3)

print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0)) # 행 기준 (행을 고정하고, 같은 열에서 가장 큰값)
print(np.min(arr, axis=1)) # 열 기준 (열을 고정하고, 같은 행게서 가장 작은값)

6
1
[4 5 6]
[1 4]


In [92]:
# 합계
print(arr)
print(arr.sum())
print(np.sum(arr))

print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1 2 3]
 [4 5 6]]
21
21
[5 7 9]
[ 6 15]


In [91]:
# 평균
print(arr.mean())
print(np.mean(arr))

print(arr.mean(axis=0))
print(arr.mean(axis=1))

3.5
3.5
[2.5 3.5 4.5]
[2. 5.]
