### ndarray 정렬

In [2]:
import numpy as np

##### 1차원 배열 정렬

In [18]:
arr=np.random.randint(1,11,10)
print(arr)

[ 2  8  3  3  7  3  2 10  3  7]


In [26]:
# np.sort(arr) : 정렬된 ndarray를 반환
# print(np.sort(arr))
# arr=np.sort(arr)
print(np.sort(arr))
print(arr)

[ 2  2  3  3  3  3  7  7  8 10]
[ 2  2  3  3  3  3  7  7  8 10]


In [27]:
np.sort(arr[::-1])

array([ 2,  2,  3,  3,  3,  3,  7,  7,  8, 10], dtype=int32)

---

##### 2차원 배열 정렬

In [ ]:
arr=np.random.randint(10,size=(3,4)) # 0 이상 10 미만
arr

array([[3, 6, 6, 0],
       [6, 8, 2, 7],
       [9, 8, 5, 6]], dtype=int32)

In [ ]:
np.sort(arr) # 기본값은 axis=1 인 경우

array([[0, 3, 6, 6],
       [2, 6, 7, 8],
       [5, 6, 8, 9]], dtype=int32)

In [ ]:
print(np.sort(arr, axis=0)) # 헹 빙행 장렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[3 6 2 0]
 [6 8 5 6]
 [9 8 6 7]]
[[0 3 6 6]
 [2 6 7 8]
 [5 6 8 9]]


In [35]:
print(np.sort(arr,axis=None)) # axis=NONE => 축이 무시되며, 차원이 사라진다. (행/열 구분없이 모든 값 정렬)
print(np.sort(arr,axis=None).shape)

[0 2 3 5 6 6 6 6 7 8 8 9]
(12,)


##### np.argsort
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [37]:
arr=np.array([100,400,200,300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [56]:
names=np.array(['리사','로제','제니','지수'])
album_sales=np.array([900,870,1000,670])
print(np.sort(album_sales)[::-1])
print(np.argsort(album_sales)[::-1])

sales_desc=np.argsort(album_sales)[::-1]
names[sales_desc]

[1000  900  870  670]
[2 0 1 3]


array(['제니', '리사', '로제', '지수'], dtype='<U2')

In [ ]:
# 2차원 배열에서 argsort
arr=np.array([[2025,2,28],[17,18,30]])

print(np.argsort(arr))
print(np.argsort(arr,axis=1)) # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr,axis=0)) # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[1 2 0]
 [0 1 2]]
[[1 2 0]
 [0 1 2]]
[[1 0 0]
 [0 1 1]]
